### ISSUE TITLE
Issue running demo on Chrome locally

### ISSUE THREAD

**Issue by bcwik9** [schmich/instascan#102]
I downloaded the demo HTML along with the `instascan.min.js` file, and opened the webpage in Chrome. It asks for permissions for my webcam, but then nothing happens. Im getting this error in the console:
```
Invalid asm.js: instascan.min.js:18
Type mismatch in assignment: test.html:1 
```

Im running locally just to test functionality without having to use HTTPS. Is anyone else able to do this?

**Comment by bcwik9** [comment]
I also tried https://github.com/dwa012/html5-qrcode and experienced the same issue.

Oddly enough, the demo page works for instascan when I go to https://schmich.github.io/instascan/.

**Comment by iamunknown2** [comment]
Ditto - I have this same problem as well.

**Comment by bcwik9** [comment]
I was never able to solve the issue. However I did get it working using a self signed SSL cert. Definitely not the same as testing locally without a cert at all, but it at least is a temporary workaround.

**Comment by leplatrem** [comment]
I had no problem running a simple http server in the local folder:

```
$ cd path/to/folder/
$ python3 -m http.server 300
```
Go to http://localhost:3000

**Comment by dhcmega** [comment]
Copied the one from the demo site, and it worked.

**Comment by stepri** [comment]
Same problem here, also causes CPU 100%

**Comment by youneskasri** [comment]
Same problem :/

**Comment by husani** [comment]
Same. I have a self-signed certificate, if that's relevant -- and have a root CA trusted by my mac's security settings. Instascan will detect a QR code perfectly fine, but the video preview does not work.

**Comment by chris-gunawardena** [comment]
I think this was a uglifyJS issue, building instascan.min.js new with `gulp release` seems to fix this.

**Comment by GunaOptisol** [comment]
How to fix the following error on instascan:

instascan.min.js:10 Uncaught abort() at Error
    at jsStackTrace (https://rawgit.com/schmich/instascan-builds/master/instascan.min.js:9:27133)
    at stackTrace (https://rawgit.com/schmich/instascan-builds/master/instascan.min.js:9:27306)
    at Object.abort (https://rawgit.com/schmich/instascan-builds/master/instascan.min.js:10:30556)
    at _abort (https://rawgit.com/schmich/instascan-builds/master/instascan.min.js:10:15029)
    at $q (https://rawgit.com/schmich/instascan-builds/master/instascan.min.js:40:17470)
    at vY (https://rawgit.com/schmich/instascan-builds/master/instascan.min.js:38:13302)
    at Array.zN (https://rawgit.com/schmich/instascan-builds/master/instascan.min.js:31:26766)
    at Object.xE [as dynCall_vii] (https://rawgit.com/schmich/instascan-builds/master/instascan.min.js:29:17998)
    at invoke_vii (https://rawgit.com/schmich/instascan-builds/master/instascan.min.js:10:21747)
    at BN (https://rawgit.com/schmich/instascan-builds/master/instascan.min.js:31:26450)
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.
invoke_vii @ instascan.min.js:10
QD @ instascan.min.js:31
wN @ instascan.min.js:31
value @ instascan.min.js:9
value @ instascan.min.js:9
value @ instascan.min.js:9
(anonymous) @ instascan.min.js:9
requestAnimationFrame (async)
value @ instascan.min.js:9
(anonymous) @ instascan.min.js:9
requestAnimationFrame (async)
value @ instascan.min.js:9
(anonymous) @ instascan.min.js:9
requestAnimationFrame (async)
value @ instascan.min.js:9
(anonymous) @ instascan.min.js:9
requestAnimationFrame (async)
value @ instascan.min.js:9
(anonymous) @ instascan.min.js:9
requestAnimationFrame (async)
value @ instascan.min.js:9
(anonymous) @ instascan.min.js:9
requestAnimationFrame (async)
value @ instascan.min.js:9
(anonymous) @ instascan.min.js:9
requestAnimationFrame (async)
value @ instascan.min.js:9
(anonymous) @ instascan.min.js:9
requestAnimationFrame (async)
value @ instascan.min.js:9
(anonymous) @ instascan.min.js:9
requestAnimationFrame (async)
value @ instascan.min.js:9
(anonymous) @ instascan.min.js:9
requestAnimationFrame (async)
value @ instascan.min.js:9
(anonymous) @ instascan.min.js:9
requestAnimationFrame (async)
value @ instascan.min.js:9
(anonymous) @ instascan.min.js:9
requestAnimationFrame (async)
value @ instascan.min.js:9
(anonymous) @ instascan.min.js:9
requestAnimationFrame (async)
value @ instascan.min.js:9
(anonymous) @ instascan.min.js:9
requestAnimationFrame (async)
value @ instascan.min.js:9
(anonymous) @ instascan.min.js:9
requestAnimationFrame (async)
value @ instascan.min.js:9
(anonymous) @ instascan.min.js:9
requestAnimationFrame (async)
value @ instascan.min.js:9
(anonymous) @ instascan.min.js:9
requestAnimationFrame (async)
value @ instascan.min.js:9
(anonymous) @ instascan.min.js:9
requestAnimationFrame (async)
value @ instascan.min.js:9
(anonymous) @ instascan.min.js:9
requestAnimationFrame (async)
value @ instascan.min.js:9
(anonymous) @ instascan.min.js:9
requestAnimationFrame (async)
value @ instascan.min.js:9
(anonymous) @ instascan.min.js:9
requestAnimationFrame (async)
value @ instascan.min.js:9
(anonymous) @ instascan.min.js:9
requestAnimationFrame (async)
value @ instascan.min.js:9
(anonymous) @ instascan.min.js:9
requestAnimationFrame (async)
value @ instascan.min.js:9
(anonymous) @ instascan.min.js:9
requestAnimationFrame (async)
value @ instascan.min.js:9
(anonymous) @ instascan.min.js:9
requestAnimationFrame (async)
value @ instascan.min.js:9
(anonymous) @ instascan.min.js:9
requestAnimationFrame (async)
value @ instascan.min.js:9
(anonymous) @ instascan.min.js:9
requestAnimationFrame (async)
value @ instascan.min.js:9
(anonymous) @ instascan.min.js:9
requestAnimationFrame (async)
value @ instascan.min.js:9
(anonymous) @ instascan.min.js:9
requestAnimationFrame (async)
value @ instascan.min.js:9
(anonymous) @ instascan.min.js:9
requestAnimationFrame (async)
value @ instascan.min.js:9
(anonymous) @ instascan.min.js:9
requestAnimationFrame (async)
value @ instascan.min.js:9
(anonymous) @ instascan.min.js:9
requestAnimationFrame (async)
value @ instascan.min.js:9
(anonymous) @ instascan.min.js:9

**Comment by cxa-croper** [comment]
I have the same issue along with an Uncaught OverconstrainedError in a Promise. I'm running 1.0.0 minified which I downloaded from this repo, and I'm running the demo HTML page. I am using a self-signed certificate and connecting via HTTPS. Any insights? TIA

**Comment by exqlnet** [comment]
same problem on chrome

**Comment by myusufid** [comment]
same issue here

**Comment by Ferdanielhg** [comment]
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/webrtc-adapter/3.3.3/adapter.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/vue/2.1.10/vue.min.js"></script>
<script type="text/javascript" src="https://rawgit.com/schmich/instascan-builds/master/instascan.min.js"></script>

Just add these javascript in this order and you'll get it running

**Comment by mrfrasier** [comment]
Same issue here. Downloading the js from the example fixed the problem.
