### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by navxio** [schmich/instascan#129]
at Object.<anonymous> (/home/myuser/myproject/node_modules/visibilityjs/lib/visibility.timers.js:163:4)
    at Module._compile (module.js:662:30)
    at Object.Module._extensions..js (module.js:673:10)
    at Module.load (module.js:575:32)
    at tryModuleLoad (module.js:515:12)
    at Function.Module._load (module.js:507:3)
    at Module.require (module.js:606:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/myuser/myproject/node_modules/visibilityjs/index.js:1:80)
    at Module._compile (module.js:662:30)

Tried to run a simple file test.js which contains `const Instascan = require('instascan')`

**Comment by Renzzo98** [comment]
Is there no solution to this issue? Currently having this problem
