### ISSUE TITLE
Uncaught abort() at Error (2nd time hit on instrascan)

### ISSUE THREAD

**Issue by GunaOptisol** [schmich/instascan#218]
instascan.min.js:10 Uncaught abort() at Error
    at jsStackTrace (https://rawgit.com/schmich/instascan-builds/master/instascan.min.js:9:27133)
    at stackTrace (https://rawgit.com/schmich/instascan-builds/master/instascan.min.js:9:27306)
    at Object.abort (https://rawgit.com/schmich/instascan-builds/master/instascan.min.js:10:30556)
    at _abort (https://rawgit.com/schmich/instascan-builds/master/instascan.min.js:10:15029)
    at $q (https://rawgit.com/schmich/instascan-builds/master/instascan.min.js:40:17470)
    at vY (https://rawgit.com/schmich/instascan-builds/master/instascan.min.js:38:13302)
    at Array.zN (https://rawgit.com/schmich/instascan-builds/master/instascan.min.js:31:26766)
    at Object.xE [as dynCall_vii] (https://rawgit.com/schmich/instascan-builds/master/instascan.min.js:29:17998)
    at invoke_vii (https://rawgit.com/schmich/instascan-builds/master/instascan.min.js:10:21747)
    at BN (https://rawgit.com/schmich/instascan-builds/master/instascan.min.js:31:26450)
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.
invoke_vii @ instascan.min.js:10
QD @ instascan.min.js:31
wN @ instascan.min.js:31
value @ instascan.min.js:9
value @ instascan.min.js:9
value @ instascan.min.js:9
(anonymous) @ instascan.min.js:9
requestAnimationFrame (async)
value @ instascan.min.js:9
(anonymous) @ instascan.min.js:9
requestAnimationFrame (async)
value @ instascan.min.js:9
(anonymous) @ instascan.min.js:9
requestAnimationFrame (async)
value @ instascan.min.js:9
(anonymous) @ instascan.min.js:9
requestAnimationFrame (async)
value @ instascan.min.js:9
(anonymous) @ instascan.min.js:9
requestAnimationFrame (async)
value @ instascan.min.js:9
(anonymous) @ instascan.min.js:9
requestAnimationFrame (async)
value @ instascan.min.js:9
(anonymous) @ instascan.min.js:9
requestAnimationFrame (async)
value @ instascan.min.js:9
(anonymous) @ instascan.min.js:9
requestAnimationFrame (async)
value @ instascan.min.js:9
(anonymous) @ instascan.min.js:9
requestAnimationFrame (async)
value @ instascan.min.js:9
(anonymous) @ instascan.min.js:9
requestAnimationFrame (async)
value @ instascan.min.js:9
(anonymous) @ instascan.min.js:9
requestAnimationFrame (async)
value @ instascan.min.js:9
(anonymous) @ instascan.min.js:9
requestAnimationFrame (async)
value @ instascan.min.js:9
(anonymous) @ instascan.min.js:9
requestAnimationFrame (async)
value @ instascan.min.js:9
(anonymous) @ instascan.min.js:9
requestAnimationFrame (async)
value @ instascan.min.js:9
(anonymous) @ instascan.min.js:9
requestAnimationFrame (async)
value @ instascan.min.js:9
(anonymous) @ instascan.min.js:9
requestAnimationFrame (async)
value @ instascan.min.js:9
(anonymous) @ instascan.min.js:9
requestAnimationFrame (async)
value @ instascan.min.js:9
(anonymous) @ instascan.min.js:9
requestAnimationFrame (async)
value @ instascan.min.js:9
(anonymous) @ instascan.min.js:9
requestAnimationFrame (async)
value @ instascan.min.js:9
(anonymous) @ instascan.min.js:9
requestAnimationFrame (async)
value @ instascan.min.js:9
(anonymous) @ instascan.min.js:9
requestAnimationFrame (async)
value @ instascan.min.js:9
(anonymous) @ instascan.min.js:9
requestAnimationFrame (async)
value @ instascan.min.js:9
(anonymous) @ instascan.min.js:9
requestAnimationFrame (async)
value @ instascan.min.js:9
(anonymous) @ instascan.min.js:9
requestAnimationFrame (async)
value @ instascan.min.js:9
(anonymous) @ instascan.min.js:9
requestAnimationFrame (async)
value @ instascan.min.js:9
(anonymous) @ instascan.min.js:9
requestAnimationFrame (async)
value @ instascan.min.js:9
(anonymous) @ instascan.min.js:9
requestAnimationFrame (async)
value @ instascan.min.js:9
(anonymous) @ instascan.min.js:9
requestAnimationFrame (async)
value @ instascan.min.js:9
(anonymous) @ instascan.min.js:9
requestAnimationFrame (async)
value @ instascan.min.js:9
(anonymous) @ instascan.min.js:9
requestAnimationFrame (async)
value @ instascan.min.js:9
(anonymous) @ instascan.min.js:9
requestAnimationFrame (async)
value @ instascan.min.js:9
(anonymous) @ instascan.min.js:9
requestAnimationFrame (async)
value @ instascan.min.js:9
(anonymous) @ instascan.min.js:9

![image](https://user-images.githubusercontent.com/46317578/62050307-a223b680-b22e-11e9-8bd8-0dcdca1f5751.png)

**Comment by NRiedinger** [comment]
Hey,

were you able to solve this issue? I'm currently experiencing the same.

Edit: Nevermind, my problem was that I had multiple instances of a scanner running when closing and reopening my scanner modal.

**Comment by df-rakesh** [comment]
any solution to this problem
